/**
 * Network protocol types for the simulator.
 * 
 * All messages sent over WebSocket should conform to this protocol.
 * The server is authoritative - it validates all inputs and
 * broadcasts the authoritative state.
 */

import { SimulationState, RobotInput } from '../simulation/simulationState';

/** Message types sent from client to server */
export enum ClientMessageType {
  INPUT = 'input',
 

  JOIN = 'join',
  LEAVE = 'leave',
  LOBBY_CLAIM = 'lobbyClaim',
  LOBBY_READY = 'lobbyReady',
  START_MATCH = 'startMatch',
  RESET_MATCH = 'resetMatch',
}

/** Input message from a client */
export interface InputMessage {
  type: ClientMessageType.INPUT;
  /** Unique client ID */
  clientId: string;
  /** Robot ID being controlled */
  robotId: string;
  /** Input state */
  input: RobotInput;
  /** Timestamp/sequence number for determinism */
  timestamp: number;
}

/** Join message from a client */
export interface JoinMessage {
  type: ClientMessageType.JOIN;
  /** Unique client ID (generated by client) */
  clientId: string;
  /** Desired robot ID or team assignment */
  robotId?: string;
}

/** Leave message from a client */
export interface LeaveMessage {
  type: ClientMessageType.LEAVE;
  /** Client ID */
  clientId: string;
}

export interface LobbyClaimMessage {
  type: ClientMessageType.LOBBY_CLAIM;
  clientId: string;
  robotId: string;
  initials: string;
}

export interface LobbyReadyMessage {
  type: ClientMessageType.LOBBY_READY;
  clientId: string;
  robotId: string;
  ready: boolean;
}

export interface StartMatchMessage {
  type: ClientMessageType.START_MATCH;
  clientId: string;
}

export interface ResetMatchMessage {
  type: ClientMessageType.RESET_MATCH;
  clientId: string;
}

export type ClientMessage = InputMessage | JoinMessage | LeaveMessage | LobbyClaimMessage | LobbyReadyMessage | StartMatchMessage | ResetMatchMessage;

/** Server message types */
export enum ServerMessageType {
  STATE = 'state',
  ERROR = 'error',
  JOIN_CONFIRMED = 'joinConfirmed',
}

/** Full simulation state broadcast from server */
export interface StateMessage {
  type: ServerMessageType.STATE;
  /** Current simulation state */
  state: SimulationState;
  /** Match ID or session ID */
  matchId: string;
}

/** Error message from server */
export interface ErrorMessage {
  type: ServerMessageType.ERROR;
  /** Error description */
  message: string;
}

/** Join confirmation from server */
export interface JoinConfirmedMessage {
  type: ServerMessageType.JOIN_CONFIRMED;
  /** Assigned robot ID */
  robotId: string | null;
  /** Initial simulation state */
  initialState: SimulationState;
}